Document: plexurl
Title: Debian plexurl Manual
Author: <insert document author here>
Abstract: This manual describes what plexurl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/plexurl/plexurl.sgml.gz

Format: postscript
Files: /usr/share/doc/plexurl/plexurl.ps.gz

Format: text
Files: /usr/share/doc/plexurl/plexurl.text.gz

Format: HTML
Index: /usr/share/doc/plexurl/html/index.html
Files: /usr/share/doc/plexurl/html/*.html
